project:
  type: website
  output-dir: docs

website:
  title: "Josh Cullen"
  site-url: https://joshcullen.github.io
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - [Intro to Shiny Workshop](https://joshcullen.github.io/Intro_to_Shiny) slides and materials now available. Video recording available after July 25th."
    type: success
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: Publications/index.qmd
        text: Publications
      - href: Research/index.qmd
        text: Research
      - href: software_shiny.qmd
        text: Software & Shiny Apps
      - href: Workshops/index.qmd
        text: Workshops
      
  page-footer:
    left: |
      &copy; 2024 Josh Cullen
    right: |
      This page is built with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
  google-analytics: "G-E5JJNK17PJ"
  cookie-consent: true
  open-graph: true

format:
  html:
    theme:
     light: flatly
     dark: solar
    css: styles.css
    toc: true

editor: visual

