---
title: "Software & Shiny Apps"
editor: visual
---

# Software

### [bayesmove](https://joshcullen.github.io/bayesmove/)

An R package for inferring latent behavioral states from animal movement data (telemetry and/or biologging) using non-parametric Bayesian methods. This includes features for pre-processing and analysis of data, as well as the visualization of model results. This framework does not rely on standard parametric probability density functions, which provides flexibility during model fitting. Further details regarding part of this framework can be found in [Cullen et al. (2022)](https://doi.org/10.1111/2041-210X.13745) and [Valle et al. (2022)](https://doi.org/10.1002/eap.2524).

# Shiny Applications

### [Green turtle occurrences compared to environmental layers](https://joshcullen.shinyapps.io/green_turtle_tracks/)

This app provides an interactive map for exploring green turtle (*Chelonia mydas*) tracks in the Gulf of Mexico, as well as along the coasts of Brazil and Qatar. Additionally, environmental layers (depth, net primary productivity, sea surface temperature) can be explored compared to turtle locations at each region on a monthly basis. These data are part of a study developing a transferable species distribution modeling approach.

### [Exploration of animal movement data](https://joshcullen.shinyapps.io/segmentation_of_NSD/)

This app provides an interactive and dynamic platform for users to upload and visually explore their animal telemetry dataset. Options are provided to filter by each column of the uploaded data, as well as to interactively subset the individuals and time period that is being mapped. An interactive time series plot is linked to a Leaflet map for exploring particular patterns of interest within the data.

### [Invasive species expert elicitation](https://joshcullen.shinyapps.io/invasive_expert_elicitation/)

This app was created to assist with data collection for an expert elicitation workshop on current distributions of invasive species in the southeast US. Users are first asked to define habitat suitability for a number of classes from the National Land Cover Database per species. Next, users are asked to define the intensity of species occurrence throughout the region on a raster map. I developed this novel interactive tool to be used as a layer of a Leaflet map. Additional info about the workshop can be found [here](https://joshcullen.github.io/invasive_spp_expert_elicitation/).

### [Avian influenza virus tranmission risk modeling](https://eesc.usgs.gov/aiv/indexus.html)

This app visualizes the results of a recently published paper by Prosser et al. (2024) ["*Using an adaptive modeling framework to identify avian influenza spillover risk at the wild‐domestic interface*"](https://doi.org/10.1038/s41598-024-64912-w), which provides county-level risk estimates of avian influenza virus (AIV) transmission risk from wild waterfowl to domestic poultry for each week of the year. Model input layers of estimated waterfowl abundance and weighted values for poultry are also available for exploration. Map available under the "Interactive Risk Maps" tab in the sidebar. Interactive map was created using the new [`mapgl`](https://walker-data.com/mapgl/) R package.

### [Walks with Turbo](https://joshcullen.shinyapps.io/walkingwithturbo/)

A fun app for me to explore and visualize walks with my dog Turbo. This app emphasizes style customization with CSS and simple layouts using [`{bslib}`](https://rstudio.github.io/bslib/). Photos from each walk also emphasize Turbo's style and quirkiness. The dashboard includes a summary table of the distance, duration, and elevation gain of each walk, whereas an additional plot provides an elevation profile of the selected walk show on the interactive map. A popover map at the top of the sidebar enables visualization of all recorded walks.

### [Example species occurrence dashboard](https://joshcullen.shinyapps.io/species_occurrence_dashboard/)

An example app from a Shiny workshop, which shows how to create a dashboard for a Shiny app. This includes a multi-page app on simulated data of freshwater species occurrence from surveys throughout Canadian provinces, including dynamic and interactive maps and tables. Dashboard layouts are structured through use of [`{bslib}`](https://rstudio.github.io/bslib/).